name: access to vars and secrets

on:
  push:
    branches: [ main ]

jobs:

  job_1:
    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh
    
    # per accedere alle variabili e secrets dentro il mio Environment creato nel repository
    environment: My_Environment_1

    # setto ulteriori variabili dentro l'env di esecuzione del workflow
    env:
      DAY_OF_WEEK : Monday


    steps:
    - uses: actions/checkout@v2

    - name: Accedo ai secrets e variabili del Environment del repo 
      run: |
        echo "Il valore della mia variabile d'ambiente è ${{ vars.MY_VAR_1 }}"
        echo "Il valore del mio segreto è ${{ secrets.MY_SECRET_1 }}"

    - name: Accedo alle variabili create nel workflow 
      run: echo "$DAY_OF_WEEK"


  job_2:
    runs-on: vps-ubuntu-ovh
    environment: My_Environment_1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        
    - name: Run script get_vars_from_gh_env.py
      run: python get_vars_from_gh_env.py "$DAY_OF_WEEK"
      