name: Python Request Application

on:
  push:
    branches: [ main ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Usa i miei segreti e variabili d'ambiente
      run: |
        echo "Il valore del mio segreto è ${{ secrets.MY_SECRET_1 }}"
        echo "Il valore della mia variabile d'ambiente è ${{ env.MY_ENVIRONMENT_VAR_1 }}"
      