name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run script
      run: python script.py
    

    - name: Unit-test Verify Output
      run: |
        output=$(python script.py)
        echo "Script output: $output"
        if [ "$output" = "response test: 52.159.150.27" ]; then
          echo "Output is as expected."
        else
          echo "Output is not as expected."
          exit 1
        fi      

    - name: Unit test chiamando file dal repo ./unit-test/unit_test.py
      run: python ./unit-test/unit_test.py
