name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run script
      run: python script.py
    
    - name: Verify output
      #
      ### Se diff la action esce con errore
      # < response test: 109.115.83.49
      # ---
      # > response test: x.x.x.x
      # Error: Process completed with exit code 1.
      #
      # run: |
      #   echo "response test: x.x.x.x" > expected_output.txt
      #   echo "response test: 109.115.83.49" > output.txt
      #   diff output.txt expected_output.txt
      run: |
        echo "response test: 109.115.83.49" > expected_output.txt
        echo "response test: 109.115.83.49" > output.txt
        diff output.txt expected_output.txt
